#include <iostream>
using namespace std;
void main() {
    setlocale(LC_CTYPE, "russian");
    int i, m;
    cout << "Введите число от 1 до 30:" << endl;
    cin >> i;
    switch(i){
            case 1:cout << "Один" << endl;
        break;
            case 2:cout << "Два" << endl;
        break;
            case 3:cout << "Три" << endl;
        break;
            case 4:cout << "Четыре" << endl;
        break;
            case 5:cout << "Пять" << endl;
        break;
            case 6:cout << "Шесть" << endl;
        break;
            case 7:cout << "Семь" << endl;
        break;
            case 8:cout << "Восемь" << endl;
        break;
           сase 9:cout << "Девять" << endl;
        break;
            case 10:cout << "Десять" << endl;
        break;
            case 11:cout << "Одиннадцать" << endl;
        break;
            case 12:cout << "Двенадцать" << endl;
        break;       
            case 13:cout << "Тринадцать" << endl;
        break;       
            case 14:cout << "Четырнадцать" << endl;
        break;       
            case 15:cout << "Пятнадцать << endl;
        break;       
            case 16:cout << "Шестнадцать" << endl;
        break; 
            case 17:cout << "Семнадцать" << endl;
        break;       
            case 18:cout << "Восемнадцать" << endl;
        break;       
            case 19:cout << "Девятнадцать" << endl;
        break;       
            case 20:cout << "Двадцать" << endl;
        break;       
            case 21:cout << "Двадцать один" << endl;
        break;       
            case 22:cout << "Двадцать два" << endl;
        break;       
            case 23:cout << "Двадцать три" << endl;
        break;       
            case 24:cout << "Двадцать четыре" << endl;
        break;       
            case 25:cout << "Двадцать пять" << endl;
        break;       
            case 26:cout << "Двадцать шесть" << endl;
        break;       
            case 27:cout << "Двадцать семь" << endl;
        break;       
            case 28:cout << "Двадцать восемь" << endl;
        break;       
            case 29:cout << "Двадцать девять" << endl;
        break;       
            case 30:cout << "Тридцать" << endl;
        break;       
    }
    do {
        cout << "Хотете продолжть? 1-да;0-нет ";
        cin >> m;
        if (1 == m) {
            cout << "Введите номер действия ";
            cin >> i;
            switch (i) {
             case 1:cout << "Один" << endl;
        break;
            case 2:cout << "Два" << endl;
        break;
            case 3:cout << "Три" << endl;
        break;
            case 4:cout << "Четыре" << endl;
        break;
            case 5:cout << "Пять" << endl;
        break;
            case 6:cout << "Шесть" << endl;
        break;
            case 7:cout << "Семь" << endl;
        break;
            case 8:cout << "Восемь" << endl;
        break;
           сase 9:cout << "Девять" << endl;
        break;
            case 10:cout << "Десять" << endl;
        break;
            case 11:cout << "Одиннадцать" << endl;
        break;
            case 12:cout << "Двенадцать" << endl;
        break;       
            case 13:cout << "Тринадцать" << endl;
        break;       
            case 14:cout << "Четырнадцать" << endl;
        break;       
            case 15:cout << "Пятнадцать << endl;
        break;       
            case 16:cout << "Шестнадцать" << endl;
        break; 
            case 17:cout << "Семнадцать" << endl;
        break;       
            case 18:cout << "Восемнадцать" << endl;
        break;       
            case 19:cout << "Девятнадцать" << endl;
        break;       
            case 20:cout << "Двадцать" << endl;
        break;       
            case 21:cout << "Двадцать один" << endl;
        break;       
            case 22:cout << "Двадцать два" << endl;
        break;       
            case 23:cout << "Двадцать три" << endl;
        break;       
            case 24:cout << "Двадцать четыре" << endl;
        break;       
            case 25:cout << "Двадцать пять" << endl;
        break;       
            case 26:cout << "Двадцать шесть" << endl;
        break;       
            case 27:cout << "Двадцать семь" << endl;
        break;       
            case 28:cout << "Двадцать восемь" << endl;
        break;       
            case 29:cout << "Двадцать девять" << endl;
        break;       
            case 30:cout << "Тридцать" << endl;
        break;      
            }
        }
        if (m == 0)
            break;
    }
    while (i > 0);
}
